const jobs = [
    { 
      id: "1", 
      title: "Desenvolvedor Full Stack", 
      company: "TechCorp", 
      location: "São Paulo, SP", 
      description: "Estamos procurando um desenvolvedor Full Stack experiente para se juntar à nossa equipe dinâmica. O candidato ideal terá experiência com React, Node.js e bancos de dados SQL/NoSQL.",
      salary: "R$ 8.000 - R$ 12.000",
      benefits: ["Plano de saúde", "Vale refeição", "Gympass", "Horário flexível"],
      contractType: "CLT",
      level:"junior",
    },
    { 
      id: "2", 
      title: "Designer UX/UI", 
      company: "DesignHub", 
      location: "Rio de Janeiro, RJ", 
      description: "Procuramos um Designer UX/UI criativo para projetar interfaces intuitivas e atraentes. Experiência com Figma e Adobe Creative Suite é essencial.",
      salary: "R$ 6.000 - R$ 9.000",
      benefits: ["Plano de saúde", "Vale transporte", "Cursos de aperfeiçoamento"],
      contractType: "PJ",
      level:'Senior',
    },
   { 
      id: "3", 
      title: "Gerente de Produto", 
      company: "InnovateNow", 
      location: "Belo Horizonte, MG", 
      description: "Estamos em busca de um Gerente de Produto experiente para liderar o desenvolvimento de novos produtos inovadores. Habilidades de liderança e comunicação são cruciais.",
      salary: "R$ 12.000 - R$ 18.000",
      benefits: ["Plano de saúde e odontológico", "Participação nos lucros", "Home office parcial"],
      contractType: "CLT",
      level:"junior"
    },
    { 
      id: "4", 
      title: "Engenheiro de Dados", 
      company: "DataDrive", 
      location: "Curitiba, PR", 
      description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
      salary: "R$ 10.000 - R$ 15.000",
      benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
      contractType: "CLT",
      level:"junior"
    },
    { 
        id: "5", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"junior"
      },
      { 
        id: "6", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"junior"
      },
      { 
        id: "7", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"junior"
      },
      { 
        id: "8", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"junior"
      },
      { 
        id: "9", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"junior"
      },
      { 
        id: "10", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "11", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "12", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "13", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "14", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "15", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "16", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "17", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "18", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "19", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "20", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "21", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "22", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "23", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Pleno"
      },
      { 
        id: "24", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Junior"
      },
      { 
        id: "25", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Senior"
      },
      { 
        id: "26", 
        title: "Engenheiro de Dados", 
        company: "DataDrive", 
        location: "Curitiba, PR", 
        description: "Procuramos um Engenheiro de Dados para projetar e implementar soluções de big data. Experiência com AWS, Hadoop e Spark é desejável.",
        salary: "R$ 10.000 - R$ 15.000",
        benefits: ["Plano de saúde", "Vale alimentação", "Dia de folga no aniversário", "Auxílio educação"],
        contractType: "CLT",
        level:"Pleno"
      },   
        
  ]

  export default jobs
